### ISSUE TITLE
Hardware status name item not unique

### ISSUE THREAD

**Issue by joente** [infrasonar/esx-probe#3]
**Describe the bug**
The hardware state `name` is not correct. The item name might change all the time:

![image](https://user-images.githubusercontent.com/6572730/226921915-f0042b45-4982-4ff5-93c2-c92552ed2bd4.png)

**Comment by Koos85** [comment]
This can only be wrong for disks. The parts of that name can also be retrieved separately. Should I only fix the itemname for disks or make a new type for the disks with more metrics as seen in the itemname?

**Comment by Koos85** [comment]
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vim.host.HardwareStatusInfo.html
