### ISSUE TITLE
Negative bus reset value upon VM shutdown.

### ISSUE THREAD

**Issue by riklempens** [infrasonar/esx-probe#4]
When a VM is shutdown we sometimes observe a negative value for `disk.busReset`
A negative value seems odd for a bus reset.

Please investigate why we observe a negative value.

**Comment by Koos85** [comment]
That hostVMs check is moved to our new [vmwareguestprobe](https://github.com/infrasonar/vmwareguest-probe)
In the new probe we now filter out negative values before summation.
